name: Java CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Compile the code
        run: javac CounterApp.java

      - name: Package the app into a JAR
        run: |
          echo "Main-Class: CounterApp" > manifest.txt
          jar cvfm CounterApp.jar manifest.txt CounterApp.class

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v3
        with:
          name: CounterApp
          path: CounterApp.jar
          retention-days: 7